//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReniumLeague.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchesStadium
    {
        public int MatchID { get; set; }
        public int StadiumID { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Stadium Stadium { get; set; }
    }
}
