//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReniumLeague.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Match()
        {
            this.MatchesStadiums = new HashSet<MatchesStadium>();
        }
    
        public int id { get; set; }
        public int HomeTeamID { get; set; }
        public int GuestTeamID { get; set; }
        public string HomeTeamGoals { get; set; }
        public string GuestTeamGoals { get; set; }
        public int Attendnce { get; set; }
        public System.DateTime Date { get; set; }
        public int RoundID { get; set; }
        public int StadiumID { get; set; }
    
        public virtual Round Round { get; set; }
        public virtual Team Team { get; set; }
        public virtual Team Team1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatchesStadium> MatchesStadiums { get; set; }
    }
}
